name: pt_minori
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  ionicons: 0.2.1
  firebase_core: 1.21.0
  firebase_auth: 3.6.4
  google_sign_in: 5.4.1
  cloud_firestore: 3.4.5
  date_time_picker: 2.1.0
  intl: 0.17.0
  flutter_launcher_icons: 0.10.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/icons/icon.png
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: assets/icons/icon.png

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

