// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2I6PN_6KvcFpDdb4dczAo4GQ83Ge8nAw',
    appId: '1:839520221910:web:a9ab5366ad575d64666777',
    messagingSenderId: '839520221910',
    projectId: 'pt-minori',
    authDomain: 'pt-minori.firebaseapp.com',
    storageBucket: 'pt-minori.appspot.com',
    measurementId: 'G-4ZBESMHNPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7Uct_UFerrOs8WJDKW-1pXHO3DszNtk',
    appId: '1:839520221910:android:6434fce999c16e73666777',
    messagingSenderId: '839520221910',
    projectId: 'pt-minori',
    storageBucket: 'pt-minori.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChqKkvXxBAbvDrEdc6jKEV4wrtvM7sn2M',
    appId: '1:839520221910:ios:24fe278ed39867b9666777',
    messagingSenderId: '839520221910',
    projectId: 'pt-minori',
    storageBucket: 'pt-minori.appspot.com',
    iosClientId: '839520221910-458hc61eit2qi4vf47mm8ucjpe91llin.apps.googleusercontent.com',
    iosBundleId: 'com.minori.test.ptMinori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChqKkvXxBAbvDrEdc6jKEV4wrtvM7sn2M',
    appId: '1:839520221910:ios:24fe278ed39867b9666777',
    messagingSenderId: '839520221910',
    projectId: 'pt-minori',
    storageBucket: 'pt-minori.appspot.com',
    iosClientId: '839520221910-458hc61eit2qi4vf47mm8ucjpe91llin.apps.googleusercontent.com',
    iosBundleId: 'com.minori.test.ptMinori',
  );
}
